"""
GET YOUR PRODUCTION SMTP CREDENTIALS
Follow these EXACT steps to get the RIGHT credentials
"""

print("="*70)
print("🔑 HOW TO GET YOUR PRODUCTION SMTP CREDENTIALS")
print("="*70)
print()
print("⚠️  YOU'RE LOOKING IN THE WRONG PLACE!")
print()
print("The credentials you need are NOT:")
print("  ❌ API tokens")
print("  ❌ bulk.smtp.mailtrap.io")
print("  ❌ smtp@mailtrap.io")
print()
print("="*70)
print("✅ CORRECT STEPS TO GET SMTP CREDENTIALS:")
print("="*70)
print()
print("Step 1: Go to Mailtrap")
print("-"*70)
print("🌐 Open: https://mailtrap.io")
print()

print("Step 2: Navigate to Your Verified Domain")
print("-"*70)
print("1. Click 'Sending' in left sidebar")
print("2. Click 'Sending Domains'")
print("3. You should see: zoutedevelopers.tech with ✅ Verified")
print("4. Click on 'zoutedevelopers.tech'")
print()

print("Step 3: Find SMTP Settings")
print("-"*70)
print("Look for one of these tabs/sections:")
print("  • 'SMTP Settings'")
print("  • 'SMTP/API Settings'")
print("  • 'Credentials'")
print("  • 'Integration'")
print()

print("Step 4: Look for THIS EXACT FORMAT:")
print("-"*70)
print()
print("  SMTP Settings:")
print("  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("  Host:     live.smtp.mailtrap.io")
print("  Port:     587 (or 2525)")
print("  Username: api-xxxxxxxxxxxxxxxx")
print("  Password: xxxxxxxxxxxxxxxxxxxxxxxx")
print("  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print()
print("⚠️  KEY POINTS:")
print("   • Host should be: live.smtp.mailtrap.io")
print("   • Username starts with: api-")
print("   • Password is a LONG random string")
print()

print("="*70)
print("📋 WHAT TO COPY:")
print("="*70)
print()
print("Copy these 4 values and paste them here:")
print()
print("Host: _____________________")
print("Port: _____________________")
print("Username: _____________________")
print("Password: _____________________")
print()

print("="*70)
print("🆘 CAN'T FIND IT?")
print("="*70)
print()
print("Option A: Look for 'SMTP Credentials' section")
print("  → Should be under your verified domain")
print()
print("Option B: Look for 'Integration' tab")
print("  → Click 'SMTP' (not 'HTTP API')")
print()
print("Option C: Generate new credentials")
print("  → Look for 'Create SMTP User' or 'Generate Credentials'")
print()
print("Option D: Check under 'Streams' or 'Projects'")
print("  → Some Mailtrap accounts organize by projects")
print("  → Find your domain project and look for SMTP settings there")
print()

print("="*70)
print("📸 SCREENSHOT THIS:")
print("="*70)
print()
print("Take a screenshot of your Mailtrap page showing:")
print("  • Sending Domains section")
print("  • Your verified domain (zoutedevelopers.tech)")
print("  • Any tabs/options available when you click on it")
print()
print("This will help me guide you to the exact location!")
print()

print("="*70)
print("🎯 WHAT WE NEED:")
print("="*70)
print()
print("For your .env file, we need:")
print()
print("MAILTRAP_HOST=live.smtp.mailtrap.io")
print("MAILTRAP_PORT=587")
print("MAILTRAP_USERNAME=api-xxxxxxxxxxxxx")
print("MAILTRAP_PASSWORD=xxxxxxxxxxxxxxxx")
print("EMAIL_FROM=admin@zoutedevelopers.tech")
print()
print("="*70)
print()
print("💬 Once you find these values, paste them here and I'll")
print("   update your .env file automatically!")
print()
print("="*70)
