"""
Mailtrap DNS Setup Checker
Run this to get the exact DNS records you need to add
"""

import os
from dotenv import load_dotenv

load_dotenv()

def show_dns_setup():
    """Display DNS setup instructions"""
    
    domain = "zoutedevelopers.tech"
    
    print("="*70)
    print("🌐 DNS RECORDS TO ADD TO YOUR DOMAIN REGISTRAR")
    print("="*70)
    print()
    print(f"Domain: {domain}")
    print()
    print("⚠️  IMPORTANT: Log into your domain registrar first!")
    print("   (GoDaddy, Namecheap, Cloudflare, etc.)")
    print()
    print("="*70)
    print()
    
    # Step-by-step instructions
    print("📋 STEP 1: Go to Mailtrap Sending Section")
    print("-"*70)
    print()
    print("1. Open: https://mailtrap.io/signin")
    print("2. Click 'Sending' in left sidebar")
    print("3. Click 'Sending Domains'")
    print("4. Click '+ Add Domain' button")
    print("5. Enter: zoutedevelopers.tech")
    print("6. Click 'Add Domain'")
    print()
    print("⚠️  Mailtrap will show you EXACT DNS records to add")
    print()
    
    print("="*70)
    print("📋 STEP 2: Copy DNS Records from Mailtrap")
    print("-"*70)
    print()
    print("After adding your domain, Mailtrap will display:")
    print()
    print("✅ SPF Record (TXT)")
    print("✅ DKIM Record (TXT) - This is the LONGEST one")
    print("✅ DMARC Record (TXT)")
    print("✅ Tracking CNAME")
    print()
    print("Keep that page OPEN - you'll need to copy these!")
    print()
    
    print("="*70)
    print("📋 STEP 3: Add Records to Your Domain Registrar")
    print("-"*70)
    print()
    print("Go to your domain registrar's DNS management:")
    print()
    print("🔹 GoDaddy: Domain Settings → DNS → Manage DNS")
    print("🔹 Namecheap: Domain List → Manage → Advanced DNS")
    print("🔹 Cloudflare: DNS → Records")
    print("🔹 Google Domains: DNS → Custom Records")
    print()
    
    print("Add each record type:")
    print()
    print("Record 1: SPF (TXT)")
    print("-"*40)
    print("Type:  TXT")
    print("Name:  @ (or leave blank)")
    print("Value: [Copy from Mailtrap - starts with v=spf1]")
    print("TTL:   3600 (or Auto)")
    print()
    
    print("Record 2: DKIM (TXT)")
    print("-"*40)
    print("Type:  TXT")
    print("Name:  mailtrap._domainkey")
    print("Value: [Copy from Mailtrap - VERY LONG string]")
    print("TTL:   3600 (or Auto)")
    print()
    print("⚠️  This is the LONGEST value - copy carefully!")
    print()
    
    print("Record 3: DMARC (TXT)")
    print("-"*40)
    print("Type:  TXT")
    print("Name:  _dmarc")
    print("Value: [Copy from Mailtrap - starts with v=DMARC1]")
    print("TTL:   3600 (or Auto)")
    print()
    
    print("Record 4: Tracking (CNAME)")
    print("-"*40)
    print("Type:  CNAME")
    print("Name:  mt-link")
    print("Value: track.mailtrap.io")
    print("TTL:   3600 (or Auto)")
    print()
    
    print("="*70)
    print("📋 STEP 4: Save and Wait")
    print("-"*70)
    print()
    print("✅ Click 'Save' or 'Add Record' for each record")
    print("⏰ Wait 15 minutes to 48 hours for DNS propagation")
    print("   (Usually takes 2-6 hours)")
    print()
    print("Check propagation: https://dnschecker.org")
    print()
    
    print("="*70)
    print("📋 STEP 5: Verify Domain in Mailtrap")
    print("-"*70)
    print()
    print("After DNS propagates:")
    print()
    print("1. Go back to Mailtrap → Sending → Sending Domains")
    print("2. Your domain should show ✅ 'Verified'")
    print("3. If not verified yet, wait longer or click 'Verify'")
    print()
    
    print("="*70)
    print("📋 STEP 6: Get Production SMTP Credentials")
    print("-"*70)
    print()
    print("Once domain is ✅ VERIFIED:")
    print()
    print("1. Click on 'zoutedevelopers.tech' in Sending Domains")
    print("2. Click 'SMTP/API Settings' tab")
    print("3. You'll see NEW credentials:")
    print()
    print("   Host: live.smtp.mailtrap.io")
    print("   Port: 587 or 2525")
    print("   Username: api-xxxxxx (NEW, different from testing!)")
    print("   Password: xxxxxxxxxx (NEW!)")
    print()
    print("4. Copy these credentials")
    print()
    
    print("="*70)
    print("📋 STEP 7: Update .env File")
    print("-"*70)
    print()
    print("Update your .env file with PRODUCTION credentials:")
    print()
    print("# Mailtrap SMTP Configuration (PRODUCTION)")
    print("MAILTRAP_HOST=live.smtp.mailtrap.io")
    print("MAILTRAP_PORT=587")
    print("MAILTRAP_USERNAME=api-xxxxxx  # From Mailtrap Sending")
    print("MAILTRAP_PASSWORD=xxxxxxxxxx  # From Mailtrap Sending")
    print()
    print("# Email Configuration")
    print("EMAIL_FROM=admin@zoutedevelopers.tech")
    print("EMAIL_FROM_NAME=ZouteDevelopers")
    print()
    
    print("="*70)
    print("📋 STEP 8: Test Real Sending!")
    print("-"*70)
    print()
    print("Run your email sender:")
    print()
    print("   python email_sender.py")
    print()
    print("✅ Emails will now go to REAL recipients!")
    print("📧 Check recipient inboxes (not Mailtrap inbox)")
    print()
    
    print("="*70)
    print("🎯 QUICK REFERENCE CHECKLIST")
    print("="*70)
    print()
    print("[ ] 1. Log into Mailtrap → Sending → Add Domain")
    print("[ ] 2. Copy DNS records from Mailtrap")
    print("[ ] 3. Log into domain registrar DNS settings")
    print("[ ] 4. Add SPF record (TXT)")
    print("[ ] 5. Add DKIM record (TXT) - the long one")
    print("[ ] 6. Add DMARC record (TXT)")
    print("[ ] 7. Add Tracking record (CNAME)")
    print("[ ] 8. Save all records")
    print("[ ] 9. Wait 2-6 hours for DNS propagation")
    print("[ ] 10. Verify domain in Mailtrap shows ✅")
    print("[ ] 11. Get production SMTP credentials")
    print("[ ] 12. Update .env with new credentials")
    print("[ ] 13. Test with python email_sender.py")
    print()
    print("="*70)
    print()
    print("💡 TIP: Open 3 browser tabs:")
    print("   Tab 1: Mailtrap.io (to copy DNS records)")
    print("   Tab 2: Your domain registrar (to add records)")
    print("   Tab 3: dnschecker.org (to verify propagation)")
    print()
    print("="*70)
    print()
    print("⏰ ESTIMATED TIME:")
    print("   - Adding DNS records: 15-30 minutes")
    print("   - DNS propagation: 2-6 hours (up to 48 hours)")
    print("   - Total setup: ~6 hours from start to sending")
    print()
    print("="*70)
    print()
    print("🆘 COMMON ISSUES:")
    print()
    print("❌ Domain still not verified after 24 hours?")
    print("   → Check DNS records with dnschecker.org")
    print("   → Make sure you copied the FULL DKIM value")
    print("   → Try removing and re-adding the records")
    print()
    print("❌ Getting authentication errors after verification?")
    print("   → Make sure you're using PRODUCTION credentials")
    print("   → Check you copied the full username and password")
    print("   → Verify EMAIL_FROM matches your domain")
    print()
    print("❌ Emails going to spam?")
    print("   → Normal for first few emails")
    print("   → Recipients need to mark as 'Not Spam'")
    print("   → Make sure all 4 DNS records are added")
    print()
    print("="*70)
    print()
    print("🚀 Ready to start? Follow the steps above!")
    print()
    print("="*70)


if __name__ == "__main__":
    show_dns_setup()
